[theme]
primaryColor = "#2F3437"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F7F6F3"
textColor = "#111111"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
